import { useState, useEffect, useRef } from 'react';
import Navbar from '../components/Navbar';
import './Docs.css';

const SECTIONS = [
  { id: 'overview',        label: 'Overview',         icon: '⬡' },
  { id: 'quickstart',      label: 'Quick Start',       icon: '⚡' },
  { id: 'api-reference',   label: 'API Reference',     icon: '🔗' },
  { id: 'detection-rules', label: 'Detection Rules',   icon: '🛡️' },
  { id: 'ai-analyst',      label: 'AI Analyst',        icon: '🤖' },
  { id: 'faq',             label: 'FAQ',               icon: '❓' },
];

const API_ENDPOINTS = [
  {
    method: 'GET',
    path: '/logs',
    auth: true,
    description: 'Fetch paginated log entries. Supports filtering by severity, source IP, and time range.',
    params: [
      { name: 'page',     type: 'int',    required: false, desc: 'Page number (default: 1)' },
      { name: 'limit',    type: 'int',    required: false, desc: 'Results per page (default: 50, max: 200)' },
      { name: 'severity', type: 'string', required: false, desc: 'Filter by severity: low | medium | high | critical' },
      { name: 'source',   type: 'string', required: false, desc: 'Filter by source IP address' },
      { name: 'from',     type: 'ISO8601',required: false, desc: 'Start timestamp for range filter' },
      { name: 'to',       type: 'ISO8601',required: false, desc: 'End timestamp for range filter' },
    ],
    response: '{ "logs": [...], "total": 1024, "page": 1, "pages": 21 }',
  },
  {
    method: 'GET',
    path: '/alerts',
    auth: true,
    description: 'List all security alerts generated by the detection engine, ordered by timestamp descending.',
    params: [
      { name: 'status',   type: 'string', required: false, desc: 'Filter by status: open | approved | dismissed' },
      { name: 'severity', type: 'string', required: false, desc: 'Filter by severity level' },
      { name: 'limit',    type: 'int',    required: false, desc: 'Results per page (default: 20)' },
    ],
    response: '{ "alerts": [...], "total": 38 }',
  },
  {
    method: 'GET',
    path: '/alerts/{id}',
    auth: true,
    description: 'Retrieve full details of a single alert including AI analyst report, related log entries, and MITRE ATT&CK mapping.',
    params: [
      { name: 'id', type: 'int', required: true, desc: 'Alert ID (path parameter)' },
    ],
    response: '{ "id": 42, "type": "brute_force", "severity": "high", "analysis": { ... }, "mitre": "T1110" }',
  },
  {
    method: 'POST',
    path: '/alerts/{id}/analyze',
    auth: true,
    description: 'Trigger the AI Analyst agent to (re-)analyze an alert. The LLaMA 3.3 70B model generates a detailed report asynchronously.',
    params: [
      { name: 'id', type: 'int', required: true, desc: 'Alert ID (path parameter)' },
    ],
    response: '{ "status": "queued", "alert_id": 42, "estimated_seconds": 8 }',
  },
  {
    method: 'POST',
    path: '/alerts/{id}/approve',
    auth: true,
    description: 'Mark an alert as approved by a human analyst. Records the analyst\'s username and timestamp.',
    params: [
      { name: 'id', type: 'int', required: true, desc: 'Alert ID (path parameter)' },
    ],
    response: '{ "status": "approved", "alert_id": 42, "analyst": "jane.doe" }',
  },
  {
    method: 'POST',
    path: '/alerts/{id}/dismiss',
    auth: true,
    description: 'Dismiss an alert as a false positive. Optionally include a reason in the request body.',
    params: [
      { name: 'id',     type: 'int',    required: true,  desc: 'Alert ID (path parameter)' },
      { name: 'reason', type: 'string', required: false, desc: 'Dismissal reason (body JSON)' },
    ],
    response: '{ "status": "dismissed", "alert_id": 42 }',
  },
  {
    method: 'POST',
    path: '/auth/login',
    auth: false,
    description: 'Authenticate a user and receive a JWT Bearer token. Token expires in 24 hours.',
    params: [
      { name: 'username', type: 'string', required: true, desc: 'Account username (body JSON)' },
      { name: 'password', type: 'string', required: true, desc: 'Account password (body JSON)' },
    ],
    response: '{ "access_token": "eyJ...", "token_type": "bearer" }',
  },
  {
    method: 'POST',
    path: '/auth/register',
    auth: false,
    description: 'Register a new user account. Returns a JWT token immediately upon success.',
    params: [
      { name: 'username', type: 'string', required: true, desc: 'Desired username (body JSON)' },
      { name: 'password', type: 'string', required: true, desc: 'Account password (body JSON)' },
    ],
    response: '{ "access_token": "eyJ...", "token_type": "bearer" }',
  },
];

const FAQ_ITEMS = [
  {
    q: 'How does the detection engine work?',
    a: 'Aegis AI runs a detection loop every 10 seconds, scanning incoming log entries against a library of configurable rules. When a rule fires (e.g. ≥ 5 failed logins from the same IP in 60 s), an alert is created and queued for AI analysis.',
  },
  {
    q: 'What AI model powers the analyst?',
    a: 'The AI Analyst uses LLaMA 3.3 70B via the Groq API. The model receives a structured prompt containing the alert metadata, matched log lines, and source IP context, then returns a JSON-structured report with severity, MITRE mapping, and recommended action.',
  },
  {
    q: 'Is there a rate limit on the API?',
    a: 'Free tier: 60 requests/minute. Pro: 300 requests/minute. Enterprise: unlimited. All limits are applied per JWT token.',
  },
  {
    q: 'Can I ingest logs via the API?',
    a: 'Log ingestion via API is on the roadmap for Q3 2026. Currently, logs are ingested from a syslog-format file mounted at /logs/auth.log on the backend container.',
  },
  {
    q: 'How do I rotate my API token?',
    a: 'POST /auth/login again with your credentials to receive a fresh JWT. Your old token remains valid until its 24-hour TTL expires. Force-expiry via the Settings page will be available in v1.2.',
  },
];

function CodeBlock({ code, language = 'bash' }) {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  };
  return (
    <div className="code-block glass">
      <div className="code-block-header">
        <span className="code-lang">{language}</span>
        <button className="copy-btn" onClick={copy}>
          {copied ? '✓ Copied' : '⎘ Copy'}
        </button>
      </div>
      <pre className="code-pre"><code>{code}</code></pre>
    </div>
  );
}

function MethodBadge({ method }) {
  return <span className={`method-badge method-${method.toLowerCase()}`}>{method}</span>;
}

function FaqItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`faq-item glass ${open ? 'faq-open' : ''}`}>
      <button className="faq-question" onClick={() => setOpen(!open)}>
        <span>{q}</span>
        <span className="faq-chevron">{open ? '▲' : '▼'}</span>
      </button>
      {open && <p className="faq-answer">{a}</p>}
    </div>
  );
}

export default function Docs() {
  const [activeSection, setActiveSection] = useState('overview');
  const contentRef = useRef(null);

  // Highlight sidebar link on scroll
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      { rootMargin: '-30% 0px -60% 0px', threshold: 0 }
    );
    SECTIONS.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  const scrollTo = (id) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <>
      <div className="orb orb-cyan" style={{ position: 'fixed' }} />
      <div className="orb orb-purple" style={{ position: 'fixed' }} />
      <Navbar />
      <div className="page docs-page">

      <div className="docs-layout">
        {/* ── Left Sidebar ─────────────────────────────────── */}
        <aside className="docs-sidebar glass">
          <div className="sidebar-header">
            <span className="sidebar-icon gradient-text">⬡</span>
            <span className="sidebar-title">Documentation</span>
          </div>
          <p className="sidebar-version">v1.0 · REST API</p>
          <nav className="sidebar-nav">
            {SECTIONS.map(({ id, label, icon }) => (
              <button
                key={id}
                className={`sidebar-link ${activeSection === id ? 'active' : ''}`}
                onClick={() => scrollTo(id)}
              >
                <span className="sidebar-link-icon">{icon}</span>
                {label}
              </button>
            ))}
          </nav>
          <div className="sidebar-footer glass-glow">
            <span className="status-dot" />
            <span>API Status: <strong className="gradient-text">Operational</strong></span>
          </div>
        </aside>

        {/* ── Main Content ──────────────────────────────────── */}
        <main className="docs-content" ref={contentRef}>

          {/* ── Overview ─── */}
          <section id="overview" className="docs-section">
            <div className="section-eyebrow">
              <span className="eyebrow-dot" />
              Introduction
            </div>
            <h1 className="docs-h1">
              Aegis AI <span className="gradient-text">Documentation</span>
            </h1>
            <p className="docs-lead">
              Aegis AI is an AI-powered Security Operations Centre (SOC) platform. It combines a
              real-time log detection engine with an autonomous LLaMA 3.3 70B analyst agent that
              automatically triages, explains, and recommends actions for every alert — so your team
              can make fast, confident decisions.
            </p>

            <div className="info-cards">
              <div className="info-card glass-glow">
                <div className="info-card-icon">⚡</div>
                <div>
                  <strong>Real-time</strong>
                  <p>Detection engine runs every 10 seconds</p>
                </div>
              </div>
              <div className="info-card glass-glow">
                <div className="info-card-icon">🤖</div>
                <div>
                  <strong>LLaMA 3.3 70B</strong>
                  <p>Every alert gets full AI analysis</p>
                </div>
              </div>
              <div className="info-card glass-glow">
                <div className="info-card-icon">🗺️</div>
                <div>
                  <strong>MITRE ATT&CK</strong>
                  <p>Auto-mapped on every alert</p>
                </div>
              </div>
            </div>

            <div className="architecture-note glass">
              <span className="arch-icon">🏗️</span>
              <div>
                <strong>Architecture at a glance</strong>
                <p>
                  FastAPI backend · SQLite/Postgres storage · Groq AI inference ·
                  React + Vite frontend · Docker Compose deployment
                </p>
              </div>
            </div>
          </section>

          <div className="docs-divider" />

          {/* ── Quick Start ─── */}
          <section id="quickstart" className="docs-section">
            <div className="section-eyebrow">
              <span className="eyebrow-dot" />
              Quick Start
            </div>
            <h2 className="docs-h2">Get up and running in minutes</h2>
            <p className="docs-body">
              Aegis AI ships as a Docker Compose stack. Clone the repository, add your Groq API key,
              and you're live.
            </p>

            <h3 className="docs-h3">1 · Clone &amp; configure</h3>
            <CodeBlock language="bash" code={`git clone https://github.com/divp112005-coder/Aegis_AI.git
cd Aegis_AI

# Copy the environment template and fill in your keys
cp backend/.env.example backend/.env`} />

            <h3 className="docs-h3">2 · Add your Groq API key</h3>
            <p className="docs-body">Open <code className="inline-code">backend/.env</code> and set:</p>
            <CodeBlock language="env" code={`GROQ_API_KEY=gsk_your_key_here
SECRET_KEY=change_me_to_a_random_string
DATABASE_URL=sqlite:///./aegis.db`} />

            <h3 className="docs-h3">3 · Start with Docker Compose</h3>
            <CodeBlock language="bash" code={`docker compose up --build

# Frontend  → http://localhost:5173
# Backend   → http://localhost:8000
# API docs  → http://localhost:8000/docs`} />

            <h3 className="docs-h3">4 · Authenticate via the API</h3>
            <CodeBlock language="bash" code={`# Register a new account
curl -X POST http://127.0.0.1:8000/auth/register \\
  -H "Content-Type: application/json" \\
  -d '{"username": "analyst", "password": "s3cur3!"}'

# → {"access_token": "eyJ...", "token_type": "bearer"}

# Use the token in subsequent requests
export TOKEN="eyJ..."
curl http://127.0.0.1:8000/alerts \\
  -H "Authorization: Bearer $TOKEN"`} />
          </section>

          <div className="docs-divider" />

          {/* ── API Reference ─── */}
          <section id="api-reference" className="docs-section">
            <div className="section-eyebrow">
              <span className="eyebrow-dot" />
              API Reference
            </div>
            <h2 className="docs-h2">REST API</h2>
            <p className="docs-body">
              All endpoints are served from <code className="inline-code">http://127.0.0.1:8000</code>.
              Protected endpoints require an <code className="inline-code">Authorization: Bearer &lt;token&gt;</code> header
              obtained from <code className="inline-code">POST /auth/login</code>.
            </p>

            <div className="api-base-url glass">
              <span className="api-base-label">Base URL</span>
              <code className="api-base-code">http://127.0.0.1:8000</code>
            </div>

            <div className="endpoints-list">
              {API_ENDPOINTS.map((ep, i) => (
                <div key={i} className="endpoint-card glass">
                  <div className="endpoint-header">
                    <MethodBadge method={ep.method} />
                    <code className="endpoint-path">{ep.path}</code>
                    {ep.auth && (
                      <span className="auth-badge">
                        🔒 Auth required
                      </span>
                    )}
                  </div>

                  <p className="endpoint-desc">{ep.description}</p>

                  {ep.params.length > 0 && (
                    <div className="params-table-wrap">
                      <table className="params-table">
                        <thead>
                          <tr>
                            <th>Parameter</th>
                            <th>Type</th>
                            <th>Required</th>
                            <th>Description</th>
                          </tr>
                        </thead>
                        <tbody>
                          {ep.params.map((p, j) => (
                            <tr key={j}>
                              <td><code className="param-name">{p.name}</code></td>
                              <td><span className="param-type">{p.type}</span></td>
                              <td>
                                <span className={`param-req ${p.required ? 'req-yes' : 'req-no'}`}>
                                  {p.required ? 'Yes' : 'No'}
                                </span>
                              </td>
                              <td className="param-desc-cell">{p.desc}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}

                  <div className="endpoint-response">
                    <span className="response-label">Sample response</span>
                    <CodeBlock language="json" code={ep.response} />
                  </div>
                </div>
              ))}
            </div>
          </section>

          <div className="docs-divider" />

          {/* ── Detection Rules ─── */}
          <section id="detection-rules" className="docs-section">
            <div className="section-eyebrow">
              <span className="eyebrow-dot" />
              Detection Rules
            </div>
            <h2 className="docs-h2">How alerts are generated</h2>
            <p className="docs-body">
              Aegis AI ships with a set of built-in detection rules. Each rule defines a pattern to
              match against log lines, a threshold, and a time window. When a rule fires, an alert is
              created and queued for AI analysis.
            </p>

            <div className="rules-grid">
              {[
                {
                  name: 'Brute Force',
                  tag: 'T1110',
                  color: 'red',
                  icon: '🔨',
                  desc: 'Detects ≥ 5 failed SSH/login attempts from the same source IP within a 60-second window.',
                  threshold: '5 failures / 60 s',
                },
                {
                  name: 'Port Scan',
                  tag: 'T1046',
                  color: 'amber',
                  icon: '🔍',
                  desc: 'Flags connections to ≥ 15 distinct ports from the same source IP within a 30-second window.',
                  threshold: '15 ports / 30 s',
                },
                {
                  name: 'Anomalous Login Time',
                  tag: 'T1078',
                  color: 'lavender',
                  icon: '🕑',
                  desc: 'Alerts on successful logins occurring between 00:00–05:00 local time for accounts with no prior night activity.',
                  threshold: 'Login 00:00–05:00',
                },
                {
                  name: 'Privilege Escalation',
                  tag: 'T1068',
                  color: 'rose',
                  icon: '⬆️',
                  desc: 'Detects sudo or su usage followed by a sensitive file access within 120 seconds.',
                  threshold: 'sudo → sensitive / 120 s',
                },
              ].map((rule) => (
                <div key={rule.name} className="rule-card glass-glow">
                  <div className="rule-header">
                    <span className="rule-icon">{rule.icon}</span>
                    <div>
                      <div className="rule-name">{rule.name}</div>
                      <div className={`rule-mitre mitre-${rule.color}`}>{rule.tag}</div>
                    </div>
                  </div>
                  <p className="rule-desc">{rule.desc}</p>
                  <div className="rule-threshold glass">
                    <span className="threshold-label">Threshold</span>
                    <code className="threshold-value">{rule.threshold}</code>
                  </div>
                </div>
              ))}
            </div>

            <h3 className="docs-h3">Custom rules (Pro &amp; Enterprise)</h3>
            <p className="docs-body">
              Custom rules are defined in YAML and hot-reloaded by the detection engine without a
              restart. Below is the schema:
            </p>
            <CodeBlock language="yaml" code={`# aegis-rules.yml
rules:
  - name: "Repeated sudo failures"
    mitre: "T1068"
    severity: high
    pattern:
      log_type: auth
      match: "sudo.*incorrect password"
    threshold:
      count: 3
      window_seconds: 120
      group_by: source_ip
    action: alert`} />
          </section>

          <div className="docs-divider" />

          {/* ── AI Analyst ─── */}
          <section id="ai-analyst" className="docs-section">
            <div className="section-eyebrow">
              <span className="eyebrow-dot" />
              AI Analyst
            </div>
            <h2 className="docs-h2">The autonomous AI agent</h2>
            <p className="docs-body">
              When an alert is created (or re-analyzed via <code className="inline-code">POST /alerts/{'{id}'}/analyze</code>),
              Aegis AI submits a structured prompt to LLaMA 3.3 70B via the Groq API. The model
              returns a JSON-structured report that is stored alongside the alert.
            </p>

            <div className="ai-pipeline glass">
              {[
                { step: '1', label: 'Alert created', icon: '🚨' },
                { step: '2', label: 'Context fetched', icon: '📋' },
                { step: '3', label: 'LLaMA 3.3 70B', icon: '🤖' },
                { step: '4', label: 'Report stored', icon: '📊' },
                { step: '5', label: 'Analyst reviews', icon: '👤' },
              ].map((s, i, arr) => (
                <div key={s.step} className="pipeline-step">
                  <div className="pipeline-node">
                    <span className="pipeline-icon">{s.icon}</span>
                    <span className="pipeline-label">{s.label}</span>
                  </div>
                  {i < arr.length - 1 && <span className="pipeline-arrow">→</span>}
                </div>
              ))}
            </div>

            <h3 className="docs-h3">Sample AI report structure</h3>
            <CodeBlock language="json" code={`{
  "summary": "Multiple failed SSH attempts detected from 45.155.205.233 (NL) targeting the 'admin' account. Pattern consistent with automated credential stuffing.",
  "severity": "HIGH",
  "confidence": 0.94,
  "mitre": {
    "technique": "T1110",
    "name": "Brute Force",
    "tactic": "Credential Access"
  },
  "context": {
    "source_ip": "45.155.205.233",
    "geo": "Netherlands",
    "target_account": "admin",
    "attempt_count": 6,
    "window_seconds": 52
  },
  "recommended_action": "Block 45.155.205.233 at the firewall level and enable MFA on the admin account. Consider reviewing SSH access policies.",
  "analyst_notes": "Foreign IP with no prior legitimate access history. Privileged account targeted. High likelihood of malicious intent."
}`} />

            <div className="ai-note glass-glow">
              <span className="ai-note-icon">💡</span>
              <div>
                <strong>Human-in-the-loop by design</strong>
                <p>
                  The AI <em>recommends</em> — your analyst decides. Every alert requires explicit
                  approval or dismissal before any action is recorded. No automated blocking occurs
                  without human confirmation.
                </p>
              </div>
            </div>
          </section>

          <div className="docs-divider" />

          {/* ── FAQ ─── */}
          <section id="faq" className="docs-section">
            <div className="section-eyebrow">
              <span className="eyebrow-dot" />
              FAQ
            </div>
            <h2 className="docs-h2">Frequently asked questions</h2>
            <div className="faq-list">
              {FAQ_ITEMS.map((item, i) => (
                <FaqItem key={i} q={item.q} a={item.a} />
              ))}
            </div>

            <div className="docs-cta glass-strong">
              <span className="cta-icon">💬</span>
              <div>
                <strong>Still have questions?</strong>
                <p>Open an issue on GitHub or start a discussion — we respond within 24 hours.</p>
              </div>
              <a
                href="https://github.com/divp112005-coder/Aegis_AI/issues"
                target="_blank"
                rel="noreferrer"
                className="btn btn-primary"
              >
                Open GitHub Issue →
              </a>
            </div>
          </section>

          {/* ── Footer ─── */}
          <footer className="footer">
            <div className="footer-brand">
              <span className="brand-icon">⬡</span>
              <span className="gradient-text" style={{ fontWeight: 700 }}>Aegis AI</span>
            </div>
            <p className="footer-copy">© 2026 Aegis AI. Built with FastAPI, React, and LLaMA 3.3.</p>
            <div className="footer-links">
              <a href="/docs">Docs</a>
              <a href="/pricing">Pricing</a>
              <a href="https://github.com/divp112005-coder/Aegis_AI" target="_blank" rel="noreferrer">GitHub</a>
            </div>
          </footer>
        </main>
      </div>
      </div>
    </>
  );
}
